// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaU5bz220DpUtVdK4jbmODPbyH6Uvk8Tc',
    appId: '1:951657633245:web:bbb611ef2ddcb29d21d234',
    messagingSenderId: '951657633245',
    projectId: 'account-flow-473s7o',
    authDomain: 'account-flow-473s7o.firebaseapp.com',
    storageBucket: 'account-flow-473s7o.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmaA-J-GMB-W4_U_4VfJ7yLp5NPeG1ImM',
    appId: '1:951657633245:android:93df370600860f1921d234',
    messagingSenderId: '951657633245',
    projectId: 'account-flow-473s7o',
    storageBucket: 'account-flow-473s7o.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIuFnV6LjrG3f6q8L4RIXYmKazKMsi6oM',
    appId: '1:951657633245:ios:917643af444239db21d234',
    messagingSenderId: '951657633245',
    projectId: 'account-flow-473s7o',
    storageBucket: 'account-flow-473s7o.firebasestorage.app',
    iosClientId: '951657633245-58f5d8bcisii7tbuhsvcf3cjpsvfl9ob.apps.googleusercontent.com',
    iosBundleId: 'com.example.setu3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIuFnV6LjrG3f6q8L4RIXYmKazKMsi6oM',
    appId: '1:951657633245:ios:917643af444239db21d234',
    messagingSenderId: '951657633245',
    projectId: 'account-flow-473s7o',
    storageBucket: 'account-flow-473s7o.firebasestorage.app',
    iosClientId: '951657633245-58f5d8bcisii7tbuhsvcf3cjpsvfl9ob.apps.googleusercontent.com',
    iosBundleId: 'com.example.setu3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaU5bz220DpUtVdK4jbmODPbyH6Uvk8Tc',
    appId: '1:951657633245:web:95d627260380b3b321d234',
    messagingSenderId: '951657633245',
    projectId: 'account-flow-473s7o',
    authDomain: 'account-flow-473s7o.firebaseapp.com',
    storageBucket: 'account-flow-473s7o.firebasestorage.app',
  );
}
